### ISSUE TITLE
Question about port song from arcade version

### ISSUE THREAD

**Issue by magnative** [samnyan/DMTQ-Tools#1]
How to unpack .pak file from the arcade version?

I try to find the tools for it but it didn't work with all TNK arcade .pak

**Comment by rogeraabbccdd** [comment]
Tools here are for DMTQ, not for arcade TECHNIKA games.
You're barking up the wrong tree.

**Comment by magnative** [comment]
I know, I'm sorry about that.

Thank you for respond.
