### ISSUE TITLE
Technika Tune support.

### ISSUE THREAD

**Issue by handyTheLoser** [samnyan/DMTQ-Tools#2]
I was able to extract the .pt files from my copy of Technika Tune and tried your tools on them. They weren't supported, I'm guessing because of the encryption or the extra touch pad notes. Do you have any plans to support Technika Tune pt charts?

**Well let me ask this.**
I have a .pt file [from DJMAX Online] I've converted by hand to mimic what your program puts out. I compared it with a .pt file that has no trouble being converted back and forward. My .pt appears to be identical in format but it's giving me this error.

`C:\Users\nimic\Desktop\Video Game Stuff\DJMAX\DJMAX Hacking\DMTQ_Tools>bytes_to_text angel.txt
DMTQ Tools - bytes to text
This tool can help you better understanding the bytes format.
Usage: bytes_to_text.exe <anyfile>  - Convert from bytes to text interchange format.
Usage: bytes_to_text.exe <filename>.txt  - Convert from the file create by this tool back to .bytes file.

For the detailed explain please check the github repository

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at bytes_to_text.Program.Main(String[] args)`

This is the text file.
[angel.txt](https://github.com/samnyan/DMTQ-Tools/files/11245611/angel.txt)

I tried looking at your code to see if I could pin point where the error is coming from but I couldn't narrow down where the error is coming from.

I appreciate your help in advance.

**Comment by wang1989627** [comment]
I want to ask how to get the unpacked .pak
 document . I have used a lot of packaging tools to unpack the PAK file of DJMAX Technika 2，but all failed。Do you have PAK packaging tools? thanks a lot！

**Comment by handyTheLoser** [comment]
I think we should talk about this somewhere else?
email me here at nimickingdog333@gmail.com
